var possibleWords1 = [
  {name:"CAKE", image:"./images/level1/cake.png"},
  {name:"DOG", image:"./images/level1/dog.png"},
  {name:"BEAR", image:"./images/level1/bear.png"},
  {name:"BEE", image:"./images/level1/bee.png"},
  {name:"BAT", image:"./images/level1/bat.png"},
  {name:"COW", image:"./images/level1/cow.png"},
  {name:"FOX", image:"./images/level1/fox.png"},
  {name:"PIG", image:"./images/level1/pig.png"},
  {name:"EAR", image:"./images/level1/ear.png"},
  {name:"NOSE", image:"./images/level1/nose.png"},

  // {name:"HAIR", image:"./images/level1/hair.png"},
  // {name:"OWL", image:"./images/level1/owl.png"},
  // {name:"RED", image:"./images/level1/red.png"},
  // {name:"CUP", image:"./images/level1/cup.png"},
  // {name:"BALL", image:"./images/level1/ball.png"},
  // {name:"BLUE", image:"./images/level1/blue.png"},
  // {name:"FIRE", image:"./images/level1/fire.png"},
  // {name:"FISH", image:"./images/level1/fish.png"},
  // {name:"CAR", image:"./images/level1/car.png"},
  // {name:"HAND", image:"./images/level1/hand.png"},

  // {name:"GOAL", image:"./images/level1/goal.png"},
  // {name:"TREE", image:"./images/level1/tree.png"},
  // {name:"SUN", image:"./images/level1/sun.png"},
  // {name:"MILK", image:"./images/level1/milk.png"},
  // {name:"FLAG", image:"./images/level1/flag.png"},
  // {name:"BABY", image:"./images/level1/baby.png"},
  // {name:"CAT", image:"./images/level1/cat.png"},
  // {name:"FARM", image:"./images/level1/farm.png"},
  // {name:"STAR", image:"./images/level1/star.png"},
  // {name:"BOOK", image:"./images/level1/book.png"}]
]


var possibleWords2 = [
  {name:"HOUSE", image:"./images/level2/house.png"},
  {name:"HORSE", image:"./images/level2/horse.png"},
  {name:"WATER", image:"./images/level2/water.png"},
  {name:"POLICE", image:"./images/level2/police.png"},
  {name:"ROBOT", image:"./images/level2/robot.png"},
  {name:"ZEBRA", image:"./images/level2/zebra.png"},
  {name:"FLOWER", image:"./images/level2/flower.png"},
  {name:"CROSS", image:"./images/level2/cross.png"},
  {name:"CLOUD", image:"./images/level2/cloud.png"},
  {name:"GOOSE", image:"./images/level2/goose.png"},

  // {name:"SNAKE", image:"./images/level2/snake.png"},
  // {name:"MONEY", image:"./images/level2/money.png"},
  // {name:"SNAIL", image:"./images/level2/snail.png"},
  // {name:"WASHER", image:"./images/level2/washer.png"},
  // {name:"MOUSE", image:"./images/level2/mouse.png"},
  // {name:"APPLE", image:"./images/level2/apple.png"},
  // {name:"CHERRY", image:"./images/level2/cherry.png"},
  // {name:"BREAD", image:"./images/level2/bread.png"},
  // {name:"CHAIR", image:"./images/level2/chair.png"},
  // {name:"HEART", image:"./images/level2/heart.png"},

  // {name:"MIRROR", image:"./images/level2/mirror.png"},
  // {name:"MOUTH", image:"./images/level2/mouth.png"},
  // {name:"TEETH", image:"./images/level2/teeth.png"},
  // {name:"PHONE", image:"./images/level2/phone.png"},
  // {name:"PAPER", image:"./images/level2/paper.png"},
  // {name:"PLANE", image:"./images/level2/plane.png"},
  // {name:"POINT", image:"./images/level2/point.png"},
  // {name:"RIVER", image:"./images/level2/river.png"},
  // {name:"CROWN", image:"./images/level2/crown.png"},
  // {name:"CHURCH", image:"./images/level2/church.png"}]
]



var possibleWords3 = [
  {name:"PALMTREE", image:"./images/level3/palmtree.png"},
  {name:"BATTERY", image:"./images/level3/battery.png"},
  {name:"NUMBERS", image:"./images/level3/numbers.png"},
  {name:"BEDROOM", image:"./images/level3/bedroom.png"},
  {name:"CHICKEN", image:"./images/level3/chicken.png"},
  {name:"GLASSES", image:"./images/level3/glasses.png"},
  {name:"FIFTEEN", image:"./images/level3/fifteen.png"},
  {name:"PRINTER", image:"./images/level3/printer.png"},
  {name:"GIRAFFE", image:"./images/level3/giraffe.png"},
  {name:"SEAHORSE", image:"./images/level3/seahorse.png"},

  // {name:"TEACHER", image:"./images/level3/teacher.png"},
  // {name:"SIXTEEN", image:"./images/level3/sixteen.png"},
  // {name:"WEDDING", image:"./images/level3/wedding.png"},
  // {name:"BATHROOM", image:"./images/level3/bathroom.png"},
  // {name:"BASEBALL", image:"./images/level3/baseball.png"},
  // {name:"CALENDAR", image:"./images/level3/calendar.png"},
  // {name:"BIRTHDAY", image:"./images/level3/birthday.png"},
  // {name:"COMPUTER", image:"./images/level3/computer.png"},
  // {name:"EIGHTEEN", image:"./images/level3/eighteen.png"},
  // {name:"FOOTBALL", image:"./images/level3/football.png"},

  // {name:"LIGHTBULB", image:"./images/level3/lightbulb.png"},
  // {name:"THIRTEEN", image:"./images/level3/thirteen.png"},
  // {name:"CHOCOLATE", image:"./images/level3/chocolate.png"},
  // {name:"BUTTERFLY", image:"./images/level3/butterfly.png"},
  // {name:"BUBBLES", image:"./images/level3/bubbles.png"},
  // {name:"ELEFANT", image:"./images/level3/elefant.png"},
  // {name:"DOLPHIN", image:"./images/level3/dolphin.png"},
  // {name:"", image:"./images/level3/.png"},
  // {name:"", image:"./images/level3/.png"},
  // {name:"", image:"./images/level3/.png"}]
]
